name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to GHCR and Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/obeone/crawler-to-md:latest
            docker.io/obeoneorg/crawler-to-md:latest
          platforms: linux/amd64,linux/arm64,linux/i386,linux/armhf,linux/armel

      - name: Set up cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.5.2'

      - name: Sign the container image with cosign
        run: |
          cosign sign ghcr.io/obeone/crawler-to-md:latest
          cosign sign docker.io/obeoneorg/crawler-to-md:latest
        env:
          COSIGN_EXPERIMENTAL: true
