name: Build and Push Docker image

on:
  push:
    branches:
      - main

  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # For cosign

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Build Docker image
        uses: docker/build-push-action@v5 
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          load: true # Change to load instead of push
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/obeone/crawler-to-md:latest
            docker.io/obeoneorg/crawler-to-md:latest
          platforms: linux/amd64,linux/arm64,linux/i386

      - name: Log in to GitHub Container Registry and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/obeone/crawler-to-md:latest

      - name: Log in to Docker Hub and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push docker.io/obeoneorg/crawler-to-md:latest

      - name: Set up cosign
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: sigstore/cosign-installer@v3

      - name: Sign the container image with cosign
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cosign sign --yes ghcr.io/obeone/crawler-to-md@${DIGEST}
          cosign sign --yes docker.io/obeoneorg/crawler-to-md@${DIGEST}
        env:
          COSIGN_EXPERIMENTAL: true
          DIGEST: ${{ steps.docker_build.outputs.digest }}
